{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "opensearch.uname" . }}-service-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "opensearch.labels" . | nindent 4 }}
  endpoints:
  - port: {{ .Values.metricsPort }}
    interval: {{ .Values.serviceMonitor.interval }}
    path: {{ .Values.serviceMonitor.path }}
{{- end }}
